Bugfix/eip712 challenge for logs
iExecBlockchainComputing/iexec-core pull request #512
Opened 2022-06-01 13:52 UTC by jbern0rd

2022-06-01 14:50 UTC, jeremyjams approved these changes

2022-06-02 08:35 UTC, zguesmi approved these changes

2022-06-02 09:39 UTC, jbern0rd commented
@jeremyjams, @zguesmi, after discussion with pierre, it seems better to use the cheksum of an ethereum address to cache a challenge.
I added a commit with some tests

2022-06-02 10:38 UTC, zguesmi requested changes

2022-06-02 10:38 UTC, zguesmi commented on src/test/java/com/iexec/core/security/EIP712ChallengeServiceTests.java
> +    void shouldNotGetSameChallengeWithUppercaseWallet() {
Actually, from an Ethereum blockchain perspective, addresses are the same whether they are `lowercase`, `uppercase`, or `checksum`.

2022-06-02 12:50 UTC, zguesmi approved these changes

2022-06-02 13:02 UTC, merged